abbrevs:
  - name: eza
    abbr: ls
    snippet: eza
    if: (( ${+commands[eza]} ))
  # - name: z
  #   abbr: cd
  #   snippet: zi
  #   if: (( ${+commands[zi]} ))
  - name: rg
    abbr: grep
    snippet: rg
    if: (( ${+commands[rg]} ))
  - name: fd
    abbr: find
    snippet: fd
    if: (( ${+commands[fd]} ))
  - name: bat
    abbr: cat
    snippet: bat
    if: (( ${+commands[bat]} ))
  - name: git commit
    abbr: c
    snippet: commit -a -m 
    global: true
    context: '^git\s'
